name: Ci-cd 

on:
  pull_request:
    branches:
      - main
  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Chec
      uses: actions/checkout@v3

    - name: Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: |
        pytest
