name: Ci-cd 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Chec
      uses: actions/checkout@v3

    - name: Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
